In [90]:
import pandas as pd
from datetime import datetime as dt

In [91]:
data = pd.read_csv('AAPL_twitter_cleaned.csv')
data.rename(columns={'Unnamed: 0' :'sentiment_score'}, inplace=True )

In [92]:
groupbydate = data.groupby('date').mean()

In [95]:
def weighted_weekends(data):
    weighted = 0
    new_df = []
    for i in range(len(data)):
        day = dt.strptime(groupbydate.index[i], "%Y-%m-%d").weekday()
        if (day == 5): # saturday
            weighted += data.iloc[i][0] * 0.2
        elif (day == 6): # sunday
            weighted += data.iloc[i][0] * 0.3
        elif (day == 0): # monday
            weighted += data.iloc[i][0] * 0.5
            new_df.append([groupbydate.index[i], weighted])
            weighted = 0
        else:
            new_df.append([groupbydate.index[i], groupbydate.iloc[i][0]])
            
    return new_df

In [97]:
weighted_sentiment = pd.DataFrame(weighted_weekends(groupbydate), columns = ['date', 'sentiment_score'])
weighted_sentiment

         date  sentiment_score
0  2021-09-17     14878.239669
1  2021-09-20     11443.925269
2  2021-09-21      8359.845588
3  2021-09-22      6436.308411
4  2021-09-23      4366.852113
5  2021-09-24      2441.516484

In [94]:
# check if 18/9 + 19/9 + 20/9 weighted is correct
groupbydate.iloc[1][0] * 0.2 + groupbydate.iloc[2][0] * 0.3 + groupbydate.iloc[3][0] * 0.5

11443.925269171283

In [98]:
groupbydate

            sentiment_score  likes_count
date
2021-09-17     14878.239669    62.231405
2021-09-18     13005.435294    43.658824
2021-09-19     11836.203704   284.666667
2021-09-20     10583.954198    60.076336
2021-09-21      8359.845588    35.845588
2021-09-22      6436.308411    41.214953
2021-09-23      4366.852113    52.795775
2021-09-24      2441.516484    50.098901
2021-09-25       825.859375    44.968750
2021-09-26        36.500000    19.000000