In [1]:
# Raw package
import numpy as np
import pandas as pd

post = pd.read_csv("post_combined_csv.csv")
comment = pd.read_csv("comments_combined_csv.csv")

post_edit = pd.DataFrame()

C:\Users\Shawn\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [2]:
 

post["body"] = post["body"].replace("[removed]", " ")
post["body"] = post["body"].fillna(" ")
post["content_body"] = post["title"] + " " + post["body"]

In [3]:
post.head()
# # print(post_edit.iloc[3]["title"])
# print("--")
# print(post_edit.iloc[3]["content_body"])

,title,flair,score,upvote_ratio,id,subreddit,url,num_comments,body,created,content_body
0,Buy Google Business Reviews - Get Google Busin...,NaN,1,1.0,oa4lnk,investing,https://www.reddit.com/r/investing/comments/oa...,2,,2021-06-29 09:11:30,Buy Google Business Reviews - Get Google Busin...
1,Buy Positive Google Reviews - Buy 5 star Googl...,NaN,1,1.0,o9is7v,investing,https://www.reddit.com/r/investing/comments/o9...,2,,2021-06-28 11:58:34,Buy Positive Google Reviews - Buy 5 star Googl...
2,Thinking about selling $TSLA,NaN,1,1.0,o7mr80,investing,https://www.reddit.com/r/investing/comments/o7...,2,,2021-06-25 12:31:39,Thinking about selling $TSLA
3,TSLA another 100million infusion,NaN,1,1.0,o72ne0,investing,https://www.reddit.com/r/investing/comments/o7...,13,Very interesting to me that the first 15 minut...,2021-06-24 15:01:16,TSLA another 100million infusion Very interest...
4,Why is the Google ticker for CRSR lower than Y...,NaN,1,1.0,o6j32d,investing,https://www.reddit.com/r/investing/comments/o6...,3,\n\nI'm new to all this but what explains th...,2021-06-23 18:38:26,Why is the Google ticker for CRSR lower than Y...

In [4]:
post.head()

,title,flair,score,upvote_ratio,id,subreddit,url,num_comments,body,created,content_body
0,Buy Google Business Reviews - Get Google Busin...,NaN,1,1.0,oa4lnk,investing,https://www.reddit.com/r/investing/comments/oa...,2,,2021-06-29 09:11:30,Buy Google Business Reviews - Get Google Busin...
1,Buy Positive Google Reviews - Buy 5 star Googl...,NaN,1,1.0,o9is7v,investing,https://www.reddit.com/r/investing/comments/o9...,2,,2021-06-28 11:58:34,Buy Positive Google Reviews - Buy 5 star Googl...
2,Thinking about selling $TSLA,NaN,1,1.0,o7mr80,investing,https://www.reddit.com/r/investing/comments/o7...,2,,2021-06-25 12:31:39,Thinking about selling $TSLA
3,TSLA another 100million infusion,NaN,1,1.0,o72ne0,investing,https://www.reddit.com/r/investing/comments/o7...,13,Very interesting to me that the first 15 minut...,2021-06-24 15:01:16,TSLA another 100million infusion Very interest...
4,Why is the Google ticker for CRSR lower than Y...,NaN,1,1.0,o6j32d,investing,https://www.reddit.com/r/investing/comments/o6...,3,\n\nI'm new to all this but what explains th...,2021-06-23 18:38:26,Why is the Google ticker for CRSR lower than Y...

In [5]:
post_edit["content_body"] = post["content_body"]
post["created"] =  pd.to_datetime(post["created"])
post_edit["created"] =  pd.to_datetime(post["created"].dt.strftime('%Y-%m-%d'))
post_edit["score"] = post["score"]
post_edit["subreddit"] = post["subreddit"]

In [6]:

comment_edit = pd.DataFrame()
comment_edit["content_body"] = comment["body"]
comment["created"] =  pd.to_datetime(comment["created"])
comment_edit["created"] =  pd.to_datetime(comment["created"].dt.strftime('%Y-%m-%d'))
comment_edit["score"] = comment["score"]
comment_edit["subreddit"] = comment["subreddit"]

In [7]:
comment.head()

,parent_id,flair,score,comment_id,usernamesubreddit,body,created,subreddit,username
0,t1_gsqlll4,NaN,2,gsqn9dq,NaN,\~10%. It was a joke referring to the fact tha...,2021-03-29 22:44:35,investing,t2_12ldpi
1,t1_gso4ts7,NaN,1,gsqmgi2,NaN,TSLA is making people rich,2021-03-29 22:37:44,investing,t2_3lrz1qpd
2,t1_gsp5y3b,NaN,3,gsqkxtw,NaN,She probably got confused and thought she was ...,2021-03-29 22:24:48,investing,t2_12ldpi
3,t1_gspntna,NaN,2,gsqkji0,NaN,"&gt;Amazon, Google/Alphabet, Garmin\n\nThese a...",2021-03-29 22:21:25,investing,t2_12ldpi
4,t1_gsq491m,NaN,2,gsq5ddd,NaN,Well shit good luck with that! I reduced my po...,2021-03-29 20:20:04,investing,t2_ka6zo

In [8]:
comment_edit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296037 entries, 0 to 296036
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   content_body  296037 non-null  object
 1   created       296037 non-null  datetime64[ns]
 2   score         296037 non-null  int64
 3   subreddit     296037 non-null  object
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 9.0+ MB

In [9]:
reddit_edit = pd.concat([post_edit, comment_edit])

In [10]:
reddit_edit.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 342194 entries, 0 to 296036
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   content_body  342194 non-null  object
 1   created       342194 non-null  datetime64[ns]
 2   score         342194 non-null  int64
 3   subreddit     342194 non-null  object
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 13.1+ MB

In [13]:
reddit_edit.to_csv("reddit_edit.csv", index=False)